[book]
authors = ["Av1an Contributors"]
language = "en"
src = "src"
title = "Av1an Documentation"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/rust-av/Av1an"
git-repository-icon = "fa-github"